/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurveySlugRouteImport } from './routes/survey.$slug'
import { Route as BuilderIdRouteImport } from './routes/builder.$id'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppFormsRouteImport } from './routes/_app/forms'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppFormsIdResponsesRouteImport } from './routes/_app/forms_.$id.responses'
import { Route as AppFormsIdResponsesResponseIdRouteImport } from './routes/_app/forms_.$id.responses_.$responseId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveySlugRoute = SurveySlugRouteImport.update({
  id: '/survey/$slug',
  path: '/survey/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderIdRoute = BuilderIdRouteImport.update({
  id: '/builder/$id',
  path: '/builder/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsRoute = AppFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsIdResponsesRoute = AppFormsIdResponsesRouteImport.update({
  id: '/forms_/$id/responses',
  path: '/forms/$id/responses',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsIdResponsesResponseIdRoute =
  AppFormsIdResponsesResponseIdRouteImport.update({
    id: '/forms_/$id/responses_/$responseId',
    path: '/forms/$id/responses/$responseId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/forms': typeof AppFormsRoute
  '/settings': typeof AppSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/builder/$id': typeof BuilderIdRoute
  '/survey/$slug': typeof SurveySlugRoute
  '/forms/$id/responses': typeof AppFormsIdResponsesRoute
  '/forms/$id/responses/$responseId': typeof AppFormsIdResponsesResponseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/forms': typeof AppFormsRoute
  '/settings': typeof AppSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/builder/$id': typeof BuilderIdRoute
  '/survey/$slug': typeof SurveySlugRoute
  '/forms/$id/responses': typeof AppFormsIdResponsesRoute
  '/forms/$id/responses/$responseId': typeof AppFormsIdResponsesResponseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/forms': typeof AppFormsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/builder/$id': typeof BuilderIdRoute
  '/survey/$slug': typeof SurveySlugRoute
  '/_app/forms_/$id/responses': typeof AppFormsIdResponsesRoute
  '/_app/forms_/$id/responses_/$responseId': typeof AppFormsIdResponsesResponseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forms'
    | '/settings'
    | '/auth/login'
    | '/auth/signup'
    | '/builder/$id'
    | '/survey/$slug'
    | '/forms/$id/responses'
    | '/forms/$id/responses/$responseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forms'
    | '/settings'
    | '/auth/login'
    | '/auth/signup'
    | '/builder/$id'
    | '/survey/$slug'
    | '/forms/$id/responses'
    | '/forms/$id/responses/$responseId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/forms'
    | '/_app/settings'
    | '/auth/login'
    | '/auth/signup'
    | '/builder/$id'
    | '/survey/$slug'
    | '/_app/forms_/$id/responses'
    | '/_app/forms_/$id/responses_/$responseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  BuilderIdRoute: typeof BuilderIdRoute
  SurveySlugRoute: typeof SurveySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey/$slug': {
      id: '/survey/$slug'
      path: '/survey/$slug'
      fullPath: '/survey/$slug'
      preLoaderRoute: typeof SurveySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/$id': {
      id: '/builder/$id'
      path: '/builder/$id'
      fullPath: '/builder/$id'
      preLoaderRoute: typeof BuilderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forms': {
      id: '/_app/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AppFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forms_/$id/responses': {
      id: '/_app/forms_/$id/responses'
      path: '/forms/$id/responses'
      fullPath: '/forms/$id/responses'
      preLoaderRoute: typeof AppFormsIdResponsesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forms_/$id/responses_/$responseId': {
      id: '/_app/forms_/$id/responses_/$responseId'
      path: '/forms/$id/responses/$responseId'
      fullPath: '/forms/$id/responses/$responseId'
      preLoaderRoute: typeof AppFormsIdResponsesResponseIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppFormsRoute: typeof AppFormsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppFormsIdResponsesRoute: typeof AppFormsIdResponsesRoute
  AppFormsIdResponsesResponseIdRoute: typeof AppFormsIdResponsesResponseIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppFormsRoute: AppFormsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppFormsIdResponsesRoute: AppFormsIdResponsesRoute,
  AppFormsIdResponsesResponseIdRoute: AppFormsIdResponsesResponseIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  BuilderIdRoute: BuilderIdRoute,
  SurveySlugRoute: SurveySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
